#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'pi-gpio==0.8.2','console_scripts','pi_gpio_server'
__requires__ = 'pi-gpio==0.8.2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('pi-gpio==0.8.2', 'console_scripts', 'pi_gpio_server')()
    )
